Fits output vf
DESI-UR/VAST pull request #103
Opened 2023-06-30 17:43 UTC by hbrincon

2023-06-30 17:47 UTC, hbrincon commented
Combines output files of VoidFinder into a single fits file with catalog info in the header. Addresses issue #76

2024-04-17 23:02 UTC, hbrincon commented
Now writes both the VoidFinder and V2 output to single FITS files. Addresses issue #76

2024-05-28 17:01 UTC, kadglass requested changes
A thorough rewrite of the file I/O so that all output is saved in a single fits file for a given algorithm.  I have a few minor comments/requests for some of the changes before approving the pull request.

2024-06-26 16:49 UTC, hbrincon commented on python/vast/voidfinder/preprocessing.py
All the file name options (no mag cut, keep isolated, distance metric) are now reported in the primary FITS header, and so I thought we could remove them from the file name. Do we want to keep the option to name the file after these choices? I can add then back if so.

2024-06-26 16:52 UTC, hbrincon commented on python/vast/voidfinder/voidfinder.py
The maximal spheres are still being saved. The `maximal_spheres_table` table and the `myvoids_table` table are passed to the file output function `save_output_from_find_voids` for the maximals and holes respectively.

2024-06-26 16:53 UTC, hbrincon commented on example_scripts/SDSS_VoidFinder_dr7.py
See the below comment. I can add `rm_isolated=rm_isolated` back if desired

2024-06-26 17:29 UTC, hbrincon commented on example_scripts/classifyEnvironment.py
I believe that flag is what it's currently called in the master branch https://github.com/DESI-UR/VAST/blob/a3a5fac39975734cf5ebd9658921f22632f2c1d7/python/vast/voidfinder/hole_combine.py#L283

I changed the "voidID" label in the comment in `classifyEnvironment.py` to match the current label. Do we want to change the label back to "'voidID'" from the current master branch name?

2024-08-22 20:33 UTC, kadglass commented on example_scripts/classifyEnvironment.py
Double-checking in the public SDSS DR7 catalog, the column in question is named `void`.  Let's use this label for the void number associated with each hole.

2024-11-01 21:08 UTC, kadglass approved these changes
All void "flag" columns changed to "void".

2024-11-12 22:34 UTC, kadglass approved these changes
All version numbers updated, and updates are documented in the changelog.

2024-11-12 22:34 UTC, merged